Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.scriptrun = azureml.core.script_run:ScriptRun._from_run_dto with exception (packaging 23.2 (/opt/conda/envs/ptca/lib/python3.8/site-packages), Requirement.parse('packaging<=23.0,>=20.0')).
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.1072847843170166 seconds
Traceback (most recent call last):
  File "step_1a_extract_and_merge.py", line 210, in <module>
    main()
  File "step_1a_extract_and_merge.py", line 204, in main
    for _ in pool.imap_unordered(process_single_file, args_list):
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/synchronize.py", line 101, in __getstate__
    context.assert_spawning(self)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: Lock objects should only be shared between processes through inheritance
