‚öôÔ∏è Transforming structured features...
üìà Predicting categories...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
‚úÖ Finished prediction. High-confidence rows: 8427
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.11623311042785645 seconds
Traceback (most recent call last):
  File "step_5_run_inference.py", line 138, in <module>
    main(args.input_path)
  File "step_5_run_inference.py", line 80, in main
    df_out = df_out.merge(df_pred[merge_cols], on='CMPNT_MATL_NUM', how='left')
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 142, in merge
    op = _MergeOperation(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 731, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1207, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'CMPNT_MATL_NUM'

